### ISSUE TITLE
using getComputedStyle to get left in firefox differs from chrome's result.

### ISSUE THREAD

**Issue by bung87** [gtramontina/draggable.js#23]
in firefox ,the value seems same as offset left.crhome works as expect give the final value from stylesheet.

the season I've found seems like while a fixed width element horizontal center,stylesheet like `margin-left:auto;margin-right:auto;left:0` ,the firefox gives the offset left value to `left`,chrome gitves the value to `magin-left`.
firefox version:41,42
chrome version:45.0.2454.101 (64-bit)

**Comment by bung87** [comment]
I'll make a PR to solve this issue.

**Comment by dotnetCarpenter** [comment]
cool
